
lahman:
    all_star_full:
        load: {path: all_star_full.tsv.gz, sep: "\t", compression: gzip}
        schema:
          playerID: varchar
          yearID: float
          gameNum: float
          gameID: varchar
          lgID: varchar
          teamID: varchar
          GP: float
          startingPos: float
    appearances:
        load: {path: appearances.tsv.gz, sep: "\t", compression: gzip}
        schema:
            yearID: float
            teamID: varchar
            lgID: varchar
            playerID: varchar
            G_all: float
            GS: float
            G_batting: float
            G_defense: float
            G_p: float
            G_c: float
            G_1b: float
            G_2b: float
            G_3b: float
            G_ss: float
            G_lf: float
            G_cf: float
            G_rf: float
            G_of: float
            G_dh: float
            G_ph: float
            G_pr: float
    awards_managers:
        load: {path: awards_managers.tsv.gz, sep: "\t", compression: gzip}
        schema:
            playerID: varchar
            awardID: varchar
            yearID: float
            lgID: varchar
            tie: varchar
            notes: varchar
    awards_players:
        load: {path: awards_players.tsv.gz, sep: "\t", compression: gzip}
        schema:
            playerID: varchar
            awardID: varchar
            yearID: float
            lgID: varchar
            tie: varchar
            notes: varchar
    awards_share_managers:
        load: {path: awards_share_managers.tsv.gz, sep: "\t", compression: gzip}
        schema:
            awardID: varchar
            yearID: float
            lgID: varchar
            playerID: varchar
            pointsWon: float
            pointsMax: float
            votesFirst: float
    awards_share_players:
        load: {path: awards_share_players.tsv.gz, sep: "\t", compression: gzip}
        schema:
            awardID: varchar
            yearID: float
            lgID: varchar
            playerID: varchar
            pointsWon: float
            pointsMax: float
            votesFirst: float
    batting_post:
        load: {path: batting_post.tsv.gz, sep: "\t", compression: gzip}
        schema:
            yearID: float
            round: varhcar
            playerID: varchar
            teamID: varchar
            lgID: varchar
            G: float
            AB: float
            R: float
            H: float
            2B: float
            3B: float
            HR: float
            RBI: float
            SB: float
            CS: float
            BB: float
            SO: float
            IBB: float
            HBP: float
            SH: float
            SF: float
            GIDP: float
    batting:
        load: {path: batting.tsv.gz, sep: "\t", compression: gzip}
        schema:
            playerID: varchar
            yearID: float
            stint: float
            teamID: varchar
            lgID: varchar
            G: float
            AB: float
            R: float
            H: float
            2B: float
            3B: float
            HR: float
            RBI: float
            SB: float
            CS: float
            BB: float
            SO: float
            IBB: float
            HBP: float
            SH: float
            SF: float
            GIDP: float
