lahman:
    all_star_full:
        path: all_star_full.tsv.gz
    appearances:
        path: appearances.tsv.gz
    awards_managers:
        path: awards_managers.tsv.gz
    awards_players:
        path: awards_players.tsv.gz
    awards_share_managers:
        path: awards_share_managers.tsv.gz
    awards_share_players:
        path: awards_share_players.tsv.gz
    batting_post:
        path: batting_post.tsv.gz
    batting:
        path: batting.tsv.gz
    college_playing:
        path: college_playing.tsv.gz
    fielding_of_split:
        path: fielding_of_split.tsv.gz
    fielding_of:
        path: fielding_of.tsv.gz
    fielding_post:
        path: fielding_post.tsv.gz
    fielding:
        path: fielding.tsv.gz
    hall_of_fame:
        path: hall_of_fame.tsv.gz
    home_games:
        path: home_games.tsv.gz
        #This table uses '.' notation, manually swaped out for '_'
    managers_half:
        path: managers_half.tsv.gz
    managers:
        path: managers.tsv.gz
    parks:
        path: parks.tsv.gz
    people:
        path: people.tsv.gz
    pitching_post:
        path: pitching_post.tsv.gz
    pitching:
        path: pitching.tsv.gz
    salaries:
        path: salaries.tsv.gz
    schools:
        path: schools.tsv.gz
    series_post:
        path: series_post.tsv.gz
    teams_franchises:
        path: teams_franchises.tsv.gz
    teams_half:
        path: teams_half.tsv.gz
    teams:
        path: teams.tsv.gz
retrosheet:
    season_game_logs:
        table_type: partitioned
        directory: season_game_logs_dir
        iterator: year_date_int
        partitioned_by: date
        schema_override: {ump_lf_id: varchar, ump_rf_id: varchar, protest_info: varchar, forfeit_info: varchar}
    all_star_game_logs:
        path: all_star_game_logs.tsv.gz
    division_series_logs:
        path: division_series_logs.tsv.gz
    lcs_logs:
        path: lcs_logs.tsv.gz
    wild_card_logs:
        path: wild_card_logs.tsv.gz
    world_series_logs:
        path: world_series_logs.tsv.gz
    park_codes:
        path: park_codes.tsv.gz
    
#     #check null date
    schedules:
        table_type: partitioned
        directory: schedules_dir
        iterator: year_date_int
        partitioned_by: date
        schema_override: {date: varchar, date_of_makeup: varchar}
    roster:
        table_type: partitioned
        directory: rosters_dir
        iterator: year
        partitioned_by: year
statcast:
    statcast:
        table_type: partitioned
        directory: statcast_dir
        iterator: month
        partitioned_by: game_date
        schema_override: {sv_id: varchar}

fangraphs:
    batting_stats:
        table_type: partitioned
        directory: batting_stats_dir
        iterator: year
        partitioned_by: season
    pitching_stats:
        table_type: partitioned
        directory: pitching_stats_dir
        iterator: year
        partitioned_by: season
    team_batting:
        table_type: partitioned
        directory: team_batting_dir
        iterator: year
        partitioned_by: season
    team_pitching:
        table_type: partitioned
        directory: team_pitching_dir
        iterator: year
        partitioned_by: season
    team_fielding:
        table_type: partitioned
        directory: team_fielding_dir
        iterator: year
        partitioned_by: season
chadwick:
    chadwick_register:
        path: chadwick_register.tsv.gz

baseball_reference:
    standings:
        path: standings.tsv.gz
    bwar_bat:
        path: bwar_bat.tsv.gz
    bwar_pitch:
        path: bwar_pitch.tsv.gz
    batting_stats_bref:
        table_type: partitioned
        directory: batting_stats_bref_dir
        iterator: year
        partitioned_by: year
    pitching_stats_bref:
        table_type: partitioned
        directory: pitching_stats_bref_dir
        iterator: year
        partitioned_by: year
    
