
lahman:
    all_star_full:
        load: 
            path: all_star_full.tsv
            sep: "\t"
        schema:
          playerID: varchar
          yearID: float
          gameNum: float
          gameID: varchar
          lgID: varchar
          teamID: varchar
          GP: float
          startingPos: float

