lahman:
    all_star_full:
        load: {path: all_star_full.tsv.gz, sep: "\t", compression: gzip}
    appearances:
        load: {path: appearances.tsv.gz, sep: "\t", compression: gzip}
    awards_managers:
        load: {path: awards_managers.tsv.gz, sep: "\t", compression: gzip}
    awards_players:
        load: {path: awards_players.tsv.gz, sep: "\t", compression: gzip}
    awards_share_managers:
        load: {path: awards_share_managers.tsv.gz, sep: "\t", compression: gzip}
    awards_share_players:
        load: {path: awards_share_players.tsv.gz, sep: "\t", compression: gzip}
    batting_post:
        load: {path: batting_post.tsv.gz, sep: "\t", compression: gzip}
    batting:
        load: {path: batting.tsv.gz, sep: "\t", compression: gzip}
    college_playing:
        load: {path: college_playing.tsv.gz, sep: "\t", compression: gzip}
    fielding_of_split:
        load: {path: fielding_of_split.tsv.gz, sep: "\t", compression: gzip}
    fielding_of:
        load: {path: fielding_of.tsv.gz, sep: "\t", compression: gzip}
    fielding_post:
        load: {path: fielding_post.tsv.gz, sep: "\t", compression: gzip}
    fielding:
        load: {path: fielding.tsv.gz, sep: "\t", compression: gzip}
    hall_of_fame:
        load: {path: hall_of_fame.tsv.gz, sep: "\t", compression: gzip}
    home_games:
        load: {path: home_games.tsv.gz, sep: "\t", compression: gzip}
        #This table uses '.' notation, manually swaped out for '_'
    managers_half:
        load: {path: managers_half.tsv.gz, sep: "\t", compression: gzip}
    managers:
        load: {path: managers.tsv.gz, sep: "\t", compression: gzip}
    parks:
        load: {path: parks.tsv.gz, sep: "\t", compression: gzip}
    people:
        load: {path: people.tsv.gz, sep: "\t", compression: gzip}
    pitching_post:
        load: {path: pitching_post.tsv.gz, sep: "\t", compression: gzip}
    pitching:
        load: {path: pitching.tsv.gz, sep: "\t", compression: gzip}
    salaries:
        load: {path: salaries.tsv.gz, sep: "\t", compression: gzip}
    schools:
        load: {path: schools.tsv.gz, sep: "\t", compression: gzip}
    series_post:
        load: {path: series_post.tsv.gz, sep: "\t", compression: gzip}
    teams_franchises:
        load: {path: teams_franchises.tsv.gz, sep: "\t", compression: gzip}
    teams_half:
        load: {path: teams_half.tsv.gz, sep: "\t", compression: gzip}
    teams:
        load: {path: teams.tsv.gz, sep: "\t", compression: gzip}
retrosheet:
    season_game_logs:
        load: {path: season_game_logs.tsv.gz, sep: "\t", compression: gzip}
    all_star_game_logs:
        load: {path: all_star_game_logs.tsv.gz, sep: "\t", compression: gzip}
    division_series_logs:
        load: {path: division_series_logs.tsv.gz, sep: "\t", compression: gzip}
    lcs_logs:
        load: {path: lcs_logs.tsv.gz, sep: "\t", compression: gzip}
    wild_card_logs:
        load: {path: wild_card_logs.tsv.gz, sep: "\t", compression: gzip}
    world_series_logs:
        load: {path: world_series_logs.tsv.gz, sep: "\t", compression: gzip}
    park_codes:
        load: {path: park_codes.tsv.gz, sep: "\t", compression: gzip}
    schedules:
        load: {path: schedules.tsv.gz, sep: "\t", compression: gzip}
    #This could be a problem, since there is no year attached
    roster:
        load: {path: rosters.tsv.gz, sep: "\t", compression: gzip}
# statcast:
#     statcast:
#         load: {path: statcast.tsv.gz , sep: "\t", compression: gzip}

fangraphs:
    batting_stats:
        load: {path: batting_stats.tsv.gz, sep: "\t", compression: gzip}
    pitching_stats:
        load: {path: pitching_stats.tsv.gz, sep: "\t", compression: gzip}
    team_batting:
        load: {path: team_batting.tsv.gz, sep: "\t", compression: gzip}
    team_pitching:
        load: {path: team_pitching.tsv.gz, sep: "\t", compression: gzip}
    team_fielding:
        load: {path: team_fielding.tsv.gz, sep: "\t", compression: gzip}
chadwick:
    chadwick_register:
        load: {path: chadwick_register.tsv.gz, sep: "\t", compression: gzip}